name: Facebook Stream

on:
  workflow_dispatch: # يسمح بتشغيل الـ Action يدويًا

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Start Streaming to Facebook
      run: |
        ffmpeg -re -i "https://live4.beinconnect.us/YallaGoalApp/beINSports1.m3u8" \
        -vf "drawtext=text='imadTV.COM':fontcolor=white@0.6:fontsize=24:x=10:y=h-th-10" \
        -c:v libx264 -preset veryfast -crf 20 -b:v 2500k -maxrate 3000k -bufsize 5000k \
        -c:a aac -b:a 128k -ar 44100 -ac 2 -async 1 \
        -f flv "rtmps://live-api-s.facebook.com:443/rtmp/FB-122164916480260989-0-Abx9Xgzh4XRC5DzQ"
